export const ACTION_STRING = {
  authLogin: "AUTH_LOGIN",
  authRegister: "AUTH_REGISTER",
  authLogout: "AUTH_LOGOUT",
  authForgot: "AUTH_FORGOT_PASSWORD",
  authReset: "AUTH_RESET_PASSWORD",
  userPin: "PIN_USER",
  checkPin: "CHECK_PIN_USER",
  userGetprofileid: "PROFILE_USER_BY_ID",
  userDashboard: "GET_DASHBOARD",
  userHistoryNotif: "GET_HISTORY_NOTIF",
  userHistoryLimit: "GET_HISTORY_LIMIT",
  userSearch: "GET_USER",
  updateSearch: "UPDATE_SEARCH",
  userTransfer: "TRANSFER_MONEY",
  userConfirmation: "CONFIRMATION_TRANSFER",
  createTransaction: "CREATE_TRANSACTION",
  resetTransaction: "RESET_TRANSFER",
};
